[platformio]
default_envs = seeed_xiao_esp32s3

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DNUDGE_LED_PIN=D2
  -DNUDGE_BACKLIGHT_PIN=D6
  -DNUDGE_BACKLIGHT_PWM=1
lib_deps =
  https://github.com/Seeed-Studio/Seeed_GFX.git#V3.1.0
  adafruit/Adafruit seesaw Library
  adafruit/Adafruit NeoPixel
  bblanchon/ArduinoJson
  https://github.com/sparkfun/SparkFun_VEML7700_Arduino_Library.git#v2.0.1
  https://github.com/sparkfun/SparkFun_Qwiic_Buzzer_Arduino_Library.git#v1.1.0
