// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsvP-r0EygpkhH0Zwzfrl4uFzy6LcbsTQ',
    appId: '1:497972469632:web:cb87819a70c7cb8f2f6b65',
    messagingSenderId: '497972469632',
    projectId: 'nudge-discipline-app',
    authDomain: 'nudge-discipline-app.firebaseapp.com',
    storageBucket: 'nudge-discipline-app.firebasestorage.app',
    measurementId: 'G-HRMGZL1KS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBSG3vn7bB_f0jmCaGnMdcO8f-G0HlYgA',
    appId: '1:497972469632:android:11d43ae71ddb64202f6b65',
    messagingSenderId: '497972469632',
    projectId: 'nudge-discipline-app',
    storageBucket: 'nudge-discipline-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTLPcaqM2Vz5lOSAsMLHxXZuSITNumvAE',
    appId: '1:497972469632:ios:3d1ee9a876ac12ab2f6b65',
    messagingSenderId: '497972469632',
    projectId: 'nudge-discipline-app',
    storageBucket: 'nudge-discipline-app.firebasestorage.app',
    iosBundleId: 'com.example.nudge',
  );
}
